### ISSUE TITLE
Tests failt on Newlist 

### ISSUE THREAD

**Issue by matthieuHanne** [valterbarros/trackthings#1]
### Element UI version
2.4.6

### OS/Browsers version
mac os

### Vue version
2.5.17
### Steps to reproduce
try to mount a component with el-select inside throw :

```
---> <ElSelectDropdown>
       <Transition>
         <ElSelect>
           <ElFormItem>
             <ElForm>
               <Anonymous>
                 <Root>
```
TypeError: Cannot read property '$el' of undefined
    at VueComponent.mounted (/Users/mhanne/src/report-builder/viewer/node_modules/element-ui/lib/element-ui.common.js:9131:54)
    at callHook (/Users/mhanne/src/report-builder/viewer/node_modules/vue/dist/vue.runtime.common.js:2919:21)
    at Object.insert (/Users/mhanne/src/report-builder/viewer/node_modules/vue/dist/vue.runtime.common.js:4156:7)
    at invokeInsertHook (/Users/mhanne/src/report-builder/viewer/node_modules/vue/dist/vue.runtime.common.js:5958:28)

### What is Expected?
Mount le select input

### What is actually happening?
test crash.  for New list you have an idea ? i got the same bug on my app

**Comment by valterbarros** [comment]
Are you right? I run all tests in the master branch and is passing. A problem that I have with element ui on tests are solved with that https://github.com/ElemeFE/element/issues/11811
